branches:
  only:
  - master

language: r

cran: http://cran.rstudio.com
warnings_are_errors: false

r_github_packages:
  - r-lib/covr
  - r-lib/sessioninfo
  - tlverse/sl3

after_success:
  - Rscript -e 'library(covr); codecov()'

