codecov:
  token: 4808dd4e-81db-42e9-8fe3-fe5760874f97

comment: false

ignore:
  - "R/utils.R"

coverage:
  status:
    project:
      default:
        against: parent
        target: auto
        threshold: 1%
        branches:
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

    patch:
      default:
        against: parent
        target: 80%
        branches: null
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

    changes:
      default:
        against: parent
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

  flags:
    integration:
      branches:
        - master
      ignore:
        - app/ui

  ignore: # files and folders for processing
    - tests/*

  fixes:
    - "old_path::new_path"
